package com.edutrack.audit.entity;

public enum AuditAction {
    CORRECTION_APPROVED,
    CORRECTION_REJECTED,
    CORRECTION_CANCELLED,
    LEAVE_APPROVED,
    LEAVE_REJECTED,
    LEAVE_CANCELLED,
    ATTENDANCE_OVERRIDDEN,
    ATTENDANCE_POLICY_UPDATED,
    FACE_ENROLLMENT_APPROVED,
    FACE_ENROLLMENT_REJECTED,
    TEACHER_ACCOUNT_CREATED,
    TEACHER_PASSWORD_RESET,
    TEACHER_DEACTIVATED,
    TEACHER_REACTIVATED,
    STUDENT_CREATED,
    STUDENT_UPDATED,
    STUDENT_DEACTIVATED
}
